name: RSS Generate

on:
  schedule:
    - cron: '0 */2 * * *'  # 每2小时执行一次
  workflow_dispatch:        # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    env:
      RSS_S3: ${{ secrets.RSS_S3 }}  # 从 GitHub Secrets 获取 RSS_S3 值
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Checkout out branch
        uses: actions/checkout@v4
        with:
          ref: out
          path: out
          token: ${{ secrets.GITHUB_TOKEN }}  # 添加 token 用于认证
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Make shell script executable
        run: chmod +x ./main.sh
        
      - name: Run crawler
        run: ./main.sh
        
      - name: Commit and push changes
        run: |
          cd out
          # echo "当前目录内容："
          # ls -la
          # echo "Git 状态："
          # git status
          echo "尝试提交更改："
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          current_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
          git commit -m "Update RSS feeds at ${current_time}" || echo "No changes to commit"
          git push origin out || echo "推送失败"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}